[package]
name = "firewheel-macros"
version = "0.1.0"
description = "Macros for Firewheel crates"
homepage = "https://github.com/BillyDM/firewheel/blob/main/crates/firewheel-macros"
edition.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
bevy_macro_utils = "0.15"
toml_edit = { version = "0.22", default-features = false, features = ["parse"] }
