[workspace]
members = [
    "crates/firewheel",
    "crates/firewheel-cpal",
    "examples/beep_test", 
]

[workspace.dependencies]
log = "0.4.22"
rtrb = "0.3.1"
thiserror = "1.0.64"
smallvec = "1.13.2"
atomic_float = "1.1.0"