[package]
name = "firewheel"
version = "0.1.0"
description = "Flexible, high-performance, and libre audio engine for games (WIP)"
repository = "https://github.com/BillyDM/firewheel"
edition.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
exclude = ["assets/"]

# Show documentation with all features enabled on docs.rs
[package.metadata.docs.rs]
all-features = true

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Billy Messenger <60663878+BillyDM@users.noreply.github.com>"]
keywords = ["game", "audio"]
categories = ["game-development", "multimedia::audio"]

[workspace]
members = [
    "crates/firewheel-core",
    "crates/firewheel-cpal",
    "crates/firewheel-graph",
    "crates/firewheel-nodes",
    "examples/beep_test",
    "examples/play_sample",
    "examples/sampler_test",
    "examples/visual_node_graph",
]

[features]
default = ["all_nodes", "resampler", "cpal", "symphonium"]
# Enables the cpal backend
cpal = ["dep:firewheel-cpal"]
# Enables all built-in factory nodes
all_nodes = ["firewheel-nodes/all_nodes"]
# Enables resampling support when loading audio files
resampler = ["firewheel-core/resampler"]
# Enables using Symphonium for loading audio files
symphonium = ["firewheel-core/symphonium"]
# Enables the "beep test" node
beep_test_node = ["firewheel-nodes/beep_test"]
# Enables the peak meter node
peak_meter_node = ["firewheel-nodes/peak_meter"]
# Enables the sampler node
sampler_node = ["firewheel-nodes/sampler"]
# Enables the stereo to mono node
stereo_to_mono_node = ["firewheel-nodes/stereo_to_mono"]
# Enables the triple buffer nodes
triple_buffer_node = ["firewheel-nodes/triple_buffer"]
# Enables the volume pan node
volume_pan_node = ["firewheel-nodes/volume_pan"]
# Enables the volume node
volume_node = ["firewheel-nodes/volume"]

[dependencies]
firewheel-core = { path = "crates/firewheel-core", version = "0.1" }
firewheel-graph = { path = "crates/firewheel-graph", version = "0.1" }
firewheel-cpal = { path = "crates/firewheel-cpal", version = "0.1", optional = true }
firewheel-nodes = { path = "crates/firewheel-nodes", version = "0.1" }

[workspace.dependencies]
log = "0.4.22"
rtrb = "0.3.1"
thiserror = "2.0.3"
smallvec = "1.13.2"
arrayvec = "0.7.6"
atomic_float = "1.1.0"
bitflags = "2.6.0"
triple_buffer = "8"
thunderdome = "0.6.1"
crossbeam-utils = "0.8"

# Optimize all dependencies in debug builds:
[profile.dev.package."*"]
opt-level = 2
