[package]
name = "firewheel-cpal"
version = "0.2.0"
description = "cpal backend for Firewheel"
homepage = "https://github.com/BillyDM/firewheel/blob/main/crates/firewheel-cpal"
edition.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[features]

[dependencies]
firewheel-core = { path = "../firewheel-core", version = "0.2" }
firewheel-graph = { path = "../firewheel-graph", version = "0.2" }
log.workspace = true
ringbuf.workspace = true
thiserror.workspace = true
cpal = "0.15.3"
