[package]
name = "cpal_input"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
firewheel = { path = "../../", features = ["cpal_input", "cpal_resample_inputs"] }
log.workspace = true
simple-log = "2.1.0"