[package]
name = "firewheel"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true
rtrb.workspace = true
thiserror.workspace = true
smallvec.workspace = true
atomic_float.workspace = true
ahash = "0.8.11"
thunderdome = "0.6.1"
