[package]
name = "firewheel-pool"
version = "0.7.2"
description = "FX chain pools for Firewheel"
homepage = "https://github.com/BillyDM/firewheel/blob/main/crates/firewheel-pool"
repository.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

# Show documentation with all features enabled on docs.rs
[package.metadata.docs.rs]
all-features = true

[features]
default = ["std", "sampler"]
std = [
    "firewheel-core/std",
    "firewheel-graph/std",
    "firewheel-nodes/std"
]
scheduled_events = ["firewheel-core/scheduled_events", "firewheel-graph/scheduled_events"]
sampler = ["firewheel-nodes/sampler"]
spatial_basic = ["firewheel-nodes/spatial_basic"]

[dependencies]
firewheel-core = { path = "../firewheel-core", version = "0.7.2", default-features = false }
firewheel-graph = { path = "../firewheel-graph", version = "0.7.2", default-features = false }
firewheel-nodes = { path = "../firewheel-nodes", version = "0.7.2", default-features = false }
smallvec.workspace = true
thunderdome.workspace = true
thiserror.workspace = true