[package]
name = "firewheel-core"
version = "0.2.0"
description = "Shared types for Firewheel crates"
homepage = "https://github.com/BillyDM/firewheel/blob/main/crates/firewheel-core"
edition.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
symphonium = ["dep:symphonium"]
resampler = ["symphonium?/resampler"]

[dependencies]
arrayvec.workspace = true
bitflags.workspace = true
thunderdome.workspace = true
symphonium = { version = "0.3", default-features = false, optional = true }
