[package]
name = "firewheel-core"
version = "0.6.0-beta.0"
description = "Shared types for Firewheel crates"
homepage = "https://github.com/BillyDM/firewheel/blob/main/crates/firewheel-core"
repository.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

# Show documentation with all features enabled on docs.rs
[package.metadata.docs.rs]
all-features = true

[features]
# Enables scheduling events for audio nodes.
scheduled_events = []
# Enables the musical transport feature.
musical_transport = ["scheduled_events"]
symphonium = ["dep:symphonium"]
resampler = ["dep:fixed-resample", "symphonium?/resampler"]
# Enables the "arbitrary sinc" resampler in Symphonium for changing the
# pitch/length of samples at load time.
symphonium_stretch = [
    "symphonium",
    "resampler",
    "symphonium?/stretch-sinc-resampler",
]
# Enables `Component` derives for parameters.
bevy = ["dep:bevy_ecs"]
# Enables `Reflect` derives for core types.
bevy_reflect = ["dep:bevy_reflect"]

[dependencies]
firewheel-macros.workspace = true
arrayvec.workspace = true
bitflags.workspace = true
thunderdome.workspace = true
symphonium = { version = "0.6.1", default-features = false, optional = true }
fixed-resample = { version = "0.9.1", default-features = false, features = [
    "resampler",
    "fft-resampler",
], optional = true }
smallvec.workspace = true
bevy_platform.workspace = true
glam = "0.29"
bevy_ecs = { version = "0.16", default-features = false, optional = true }
bevy_reflect = { version = "0.16", default-features = false, optional = true }
# TODO: Remove this once `bevy_platform` exposes the atomic float types from `portable-atomic`.
portable-atomic = { version = "1", default-features = false, features = [
    "fallback",
    "float",
] }
