[package]
name = "firewheel-nodes"
version = "0.2.3-beta.0"
description = "Official factory nodes for the Firewheel audio engine"
homepage = "https://github.com/BillyDM/firewheel/blob/main/crates/firewheel-nodes"
edition.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = [
    "beep_test",
    "peak_meter",
    "sampler",
    "spatial_basic",
    "stereo_to_mono",
    "volume_pan",
    "volume",
]
# Enables the "beep test" node
beep_test = []
# Enables the peak meter node
peak_meter = ["dep:atomic_float"]
# Enables the sampler node
sampler = ["dep:smallvec", "dep:crossbeam-utils"]
# Enables the basic 3D spatial positioning node
spatial_basic = []
# Enables the stereo to mono node
stereo_to_mono = []
# Enables the volume pan node
volume_pan = []
# Enables the volume node
volume = []

[dependencies]
firewheel-core = { path = "../firewheel-core", version = "0.2.3-beta.0" }
atomic_float = { workspace = true, optional = true }
crossbeam-utils = { workspace = true, optional = true }
smallvec = { workspace = true, optional = true }
