[package]
name = "firewheel-nodes"
version = "0.2.4-beta.0"
description = "Official factory nodes for the Firewheel audio engine"
homepage = "https://github.com/BillyDM/firewheel/blob/main/crates/firewheel-nodes"
edition.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

# Show documentation with all features enabled on docs.rs
[package.metadata.docs.rs]
all-features = true

[features]
default = [
    "beep_test",
    "peak_meter",
    "sampler",
    "spatial_basic",
    "stream",
]
all_nodes = [
    "beep_test",
    "peak_meter",
    "sampler",
    "spatial_basic",
    "stream",
]
# Enables the "beep test" node
beep_test = []
# Enables the peak meter node
peak_meter = ["dep:atomic_float"]
# Enables the sampler node
sampler = ["dep:smallvec", "dep:crossbeam-utils"]
# Enables the basic 3D spatial positioning node
spatial_basic = []
# Enables the stream input/output nodes for sending/receiving audio
# directly to/from the audio graph from another thread.
stream = ["dep:fixed-resample"]

[dependencies]
firewheel-core = { path = "../firewheel-core", version = "0.2.4-beta.0" }
atomic_float = { workspace = true, optional = true }
crossbeam-utils = { workspace = true, optional = true }
smallvec = { workspace = true, optional = true }
fixed-resample = { workspace = true, default-features = false, features = ["resampler", "fft-resampler", "channel"], optional = true }
